### ISSUE TITLE
Strategy to locate counterexamples

### ISSUE THREAD

**Issue by StoneCypher** [pornin/paradox-compress#1]
# Tap two blue and one to cast nuh-uh

1. Create any input `n`
2. Compress `n`, yielding `n₁`
3. Compress `n₁`, yielding `n₂`
4. Iterate, compressing `nₓ`, yielding `nₓ₊₁`, terminating at `nₐ`

Concept: this compressor does not attempt to achieve infinite compressability.  ∴ there is a sequence in the compression of `n` where compression ceases, which we label `nₐ`, because Unicode is a jerk and doesn't have a subscript y or z.

# The claim

> In essence, this is transforming the question from "is it mathematically possible?" to "can I claim to do it and not being detected as a fraud?".

## The response

No.  There is a creatable counterexample at every `nₐ`.

**Comment by StoneCypher** [comment]
![image](https://user-images.githubusercontent.com/77482/135761277-c088a741-c142-4c17-ba10-7db7d6b09bab.png)

**Comment by StoneCypher** [comment]
Oh, sorry.

`nₐ` is formally defined as the point at which `nₐ₊₁.length() >= nₐ.length()`

You can find it in the wrong language thus:

```typescript
const whatever = gen_random_binary(),
      w_0      = whatever,
      w_1      = compress(whatever),
      count    = 1;

while (w_1.length < w_0.length) {
  ++count;
  w_0 = w_1;
  w_1 = compress(w_0);
}

console.log(`Random example yields counterexample after ${count} steps:

  Origin: ${whatever}

  Last compressed: ${w_0}

  Failure state: ${w_1}
`);
```

**Comment by pornin** [comment]
You might want to read again what you are trying to disclaim. I mean, even the README file! It's written in plain letter that "this is NOT infinite compression". I do not (and explain at length in the paper that I cannot) claim to reduce every input, only that that there is no strict increase in length. In your pseudocode, your `w_1.length < w_0.length` should be `w_1.length <= w_0.length`.

**Comment by StoneCypher** [comment]
> It's written in plain letter that "this is NOT infinite compression".

Please re-read the issue.  I rely on this as a supporting fact.



> In your pseudocode, your `w_1.length < w_0.length` should be `w_1.length <= w_0.length`.

That you are able to identify this suggests that you do know that this code
does, in fact, create the counterexamples you say are unfindable.

Oh well.  I tried to help.

Maybe I shouldn't have tried to be funny.

**Comment by sollyucko** [comment]
The issue would be that n_(a-1) and n_a are different inputs with the same output?

**Comment by StoneCypher** [comment]
the issue is that

1. because it isn't an infinite compressor, there must be a floor
2. if there is a floor, and if it can be found, that constitutes a
counterexample
3. the floor can be found through iterated application
